name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      project-key:
        required: true
        type: string
      sonar-check-enabled:
        required: false
        type: boolean
        default: false
      pr-title:
        required: true
        type: string
    secrets:
      github-token:
        required: true
      github-username:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate PR Title
        if: ${{ github.event_name == 'pull_request' && inputs.pr-title != '' }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PATTERN="${{ inputs.pr-title }}"

          echo "PR title: $PR_TITLE"
          echo "Expected pattern: $PATTERN"

          if [[ "$PR_TITLE" =~ $PATTERN ]]; then
            echo "✅ PR title is valid"
          else
            echo "❌ PR title does not match required pattern: $PATTERN"
            exit 1
          fi

      # code formatting using spotless
      - name: Check code formatting
        run: mvn spotless:check

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure Maven for GitHub Packages
        run: |
            mkdir -p ~/.m2
            cat <<EOF > ~/.m2/settings.xml
            <settings>
              <servers>
                <server>
                  <id>github</id>
                  <username>${{ secrets.GITHUB_USERNAME }}</username>
                  <password>${{ secrets.GITHUB_TOKEN }}</password>
                </server>
              </servers>
            </settings>
            EOF

      - name: Build with Maven
        run: mvn clean install

      - name: Print Project Key
        run: |
          echo "Project Key: ${{ inputs['project-key'] }}"

      # mvn test
      - name: Run unit tests
        run: ./mvnw test
