name: Reusable JAR Deploy

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        default: '17'
        type: string
      jar-name:
        required: true
        type: string
      jar-path:
        required: false
        default: 'target'
        type: string
      port:
        required: true
        type: string

    secrets:
      DEPLOY_KEY:
        required: true
      SERVER_HOST:
        required: true
      SERVER_USER:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Build Application
        run: ./mvnw clean package -DskipTests

      - name: Copy JAR to Remote Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: ${{ inputs.jar-path }}/${{ inputs.jar-name }}
          target: /home/${{ secrets.SERVER_USER }}/

      - name: Execute Deployment Script on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}

            echo "Backing up existing JAR..."
            mkdir -p Backup
            if [ -f ${{ inputs.jar-name }} ]; then
              mv ${{ inputs.jar-name }} Backup/${{ inputs.jar-name }}-$(date +%s)
            fi

            echo "Killing process on port ${{ inputs.port }}..."
            PID=$(lsof -t -i:${{ inputs.port }})
            if [ ! -z "$PID" ]; then
              kill -9 $PID
              echo "Process $PID killed"
            fi

            echo "Starting new JAR..."
            nohup java -jar ${{ inputs.jar-name }} > nohup.out 2>&1 &

            echo "Deployment complete"
